catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project compute_matrices
set_top compute_matrices
# v++ -g, -D, -I, --advanced.prop kernel.compute_matrices.kernel_flags
add_files "/home/inf2021/iathanasi/embedded/Embedded-Systems/lab3/lsal/hw_baseline/src/lsal.cpp" -cflags " -I /home/inf2021/iathanasi/embedded/Embedded-Systems/lab3/lsal/hw_baseline/src "
open_solution -flow_target vitis solution
set_part xc7z020clg484-1
create_clock -period 100.000000MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -disable_deadlock_detection=true
# v++ --advanced.param compiler.axiDeadLockFree
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64=0
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format ip_catalog -ipname compute_matrices
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
